### PR TITLE
refactor(app-localize-behavior): code style

### PR DESCRIPTION
**Pull request by AliMD**
I'm sorry to change code style but I think its little old!
I try to improve the style and clean the codes and improve readability
I hope you interested and merge it.
Thank you in advance

### CODE REVIEW

**Comment by merlinnot** [comment]
Don't you think it should look like
```js
/**
 * `Polymer.AppLocalizeBehavior` ...
```
?

The asterisk in the second line should be indented with one additional space.

**Comment by AliMD** [comment]
@merlinnot Thank you, its fixed

**Comment by notwaldorf** [comment]
Closing, since unfortunately we can't merge any ES6 code -- this is a hybrid element, which means that it needs to work in Polymer 1 apps as it is. IE11 does not support ES6, which means that the changes you added would break all IE11 apps, since they would need some sort of transform step.

**Comment by notwaldorf** [comment]
The point it that you can use this element _without_ transpiling it to ES5. The Polymer elements are actually not written with ES6 at all -- you won't find any classes, `let`s and `const`. They depend on which version of Polymer they're running with -- and if you're installing this element while depending on Polymer 1 (which is 100% written in ES5), then what you get is a pure ES5 codebase, that doesn't need to be compiled for IE11

**Comment by AliMD** [comment]
@notwaldorf I don't understand, all polymer elements updated to es6! who use this element separate all others ?!

**Comment by notwaldorf** [comment]
No other Polymer Elements are updated to es6; all the elements made by the Polymer team (in the PolymerElements org) are in es5. Please show me one element that has es6 syntax?

**Comment by AliMD** [comment]
@notwaldorf 
Wow! you are absolutely right!
Any plan to move to ES6?
How can I contributing ? 😋 

If I convert the codes to ES5 is it useful to merge?

**Comment by notwaldorf** [comment]
There are no plans to move to ES6 right now for these elements, since this would break backwards compatibility. As a result, you also can't convert this element to a pure Polymer 2.0 style element (since that is inherently ES6). You can write your elements in ES6 (and pure Polymer 2.0 though)

If there were any other changes that weren't these 2, then sure, we'd love to see them, though generally with how many elements we have to maintain, just refactoring PRs tend to be pretty low priority for us :(

**Pull request closed without merging**
