### PR TITLE
2.0 preview with class expressions

### PR DESCRIPTION
**Pull request by nadous**
I was looking for a way to implement "behaviors" as mixins that return class expressions, as stated in the [upgrade guide](https://www.polymer-project.org/2.0/docs/upgrade). There's a neat codelab [here](https://codelabs.developers.google.com/codelabs/polymer-2-carousel/#4) which provides the basic skeleton for a custom behavior. Since I'm new to Polymer, I have no reason to use `Polymer.LegacyElement` to patch v.1 design of older projects, so I decided to get acquainted with the train from the station I've found it. Since there's not a lot of resources on how we can upgrade the v.1 behavior design of existing elements, I've just PR this for feedback.

### CODE REVIEW

**Comment by nadous** [comment]
I signed it!

**Comment by nadous** [comment]
I signed it!

**Comment by nadous** [comment]
I signed it!

**Comment by notwaldorf** [comment]
I think this would be a 3.0 element, not a 2.0. The 2.0 versions are meant to be hybrid elements, that can work in apps that use either Polymer 1.0 or 2.0. (see https://www.polymer-project.org/1.0/blog/2016-09-09-polymer-2.0 for more details)

**Comment by nadous** [comment]
OK, I'm in the future!
```javascript
observers: [
        //the observers you know and love from Polymer
      ]
```
I've missed that part... To sum up: if I have to build a custom element, I should implement the class-based design pattern, and if I use a `Polymer 2.0-preview` component, the backwards-compatible `Polymer.Element` will be just fine, right?

**Comment by nadous** [comment]
For a reason I ignore, last month commits in #2.0-preview has broken this anyway. The ``localize`` method becoming undefined within the mixin, I guess I'll wait that _hybrid_ thing gets less schizophrenic.

**Pull request closed without merging**
